spring:
  application:
    name: attraction-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

rapidApi:
  tripAdvisor:
    key: key